name: fcp-sfd
services:
  fcp-sfd-comms:
    ports:
      - "3001:3001"
      - "9229:9229"
    volumes:
      - ./src:/home/node/src
    networks:
      - fcp-sfd

  mongodb:
    ports:
      - "27017:27017"
    networks:
      - fcp-sfd
    volumes:
      - mongodb-data:/data

  floci:
    ports:
      - "4566:4566"
    volumes:
      - floci-data:/app/data
    networks:
      - fcp-sfd

  floci-init:
    volumes:
      - ./floci/init.sh:/setup/init.sh
    networks:
      - fcp-sfd

volumes:
  mongodb-data:
  floci-data:

networks:
  fcp-sfd:
    driver: bridge
    name: fcp-sfd
