services:
  fcp-sfd-comms:
    build:
      target: development
    image: fcp-sfd-comms-development
    container_name: fcp-sfd-comms-test
    command: npm run test
    volumes:
      - ./test/:/home/node/test
      - ./coverage:/home/node/coverage
