version: '3.8'

services:
  fcp-sfd-comms:
    build:
      target: development
    image: fcp-sfd-comms-development
    container_name: fcp-sfd-comms-development
    ports:
      - '3001:3001'
    links:
      - 'localstack:localstack'
      - 'mongodb:mongodb'
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
    volumes:
      - ./src/:/home/node/src
      - ./package.json:/home/node/package.json
    env_file:
      - .env
    environment:
      PORT: 3001
      NODE_ENV: development
      MONGO_URI: mongodb://mongodb:27017/
      MONGO_DATABASE: fcp-sfd-comms
      # AWS configuration
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://localstack:4566
      # SQS/SNS configuration - only needed by the application
      SNS_TOPIC_ARN: arn:aws:sns:eu-west-2:000000000000:fcp-sfd-comms-topic
      DATA_TOPIC_ARN: arn:aws:sns:eu-west-2:000000000000:fcp-sfd-data-topic
      SQS_QUEUE_URL: http://localstack:4566/000000000000/fcp-sfd-comms-queue
      SQS_DLQ_URL: http://localstack:4566/000000000000/fcp-sfd-comms-dlq
      SQS_DLQ_ARN: arn:aws:sqs:eu-west-2:000000000000:fcp-sfd-comms-dlq
      SQS_VISIBILITY_TIMEOUT: 30
      SQS_WAIT_TIME: 20
      SQS_MAX_MESSAGES: 10
    networks:
      - cdp-tenant

  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    env_file:
      - .env
    environment:
      # Only the essential LocalStack configuration
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
      AWS_REGION: eu-west-2
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data
    restart: always

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
