name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

  workflow_dispatch:

jobs:

  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Package Version Increment
        run: |
          main_version=$(git describe origin/main --tags)
          pr_version=$(jq -r '.version' package.json)
          if [ "$pr_version" \> "$main_version" ]; then
            exit 0
          fi
          echo "Package version ($pr_version) is has not been incremented over main branch ($main_version)"
          exit 1

      - name: Build Docker Image
        run: |
          set +e
          docker build --no-cache --tag fcp-sfd-comms .
          exit $?

      - name: Run Tests
        run: |
          mkdir -p coverage
          chmod -R a+rw ./coverage
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml run --rm "fcp-sfd-comms"

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v4
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
