name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

  workflow_dispatch:

jobs:

  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Package Version Increment
        run: |
          main=$(git describe main --tags | sed 's/\.//g')
          version=$(jq -r '.version' package.json | sed 's/\.//g')
          if [[ "$main" -gt "$version" ]]; then
            echo "Package version is not incremented"
            exit 1
          fi

      - name: Build Docker Image
        run: |
          set +e
          docker build --no-cache --tag fcp-sfd-comms .
          exit $?

      - name: Run Tests
        run: |
          mkdir -p coverage
          chmod -R a+rw ./coverage
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml run --rm "fcp-sfd-comms"

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v4
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
